### PR TITLE
NXP-11348: Fix hard-coded Domain reference

### PR DESCRIPTION
**Pull request by mkalam-alami**
Updated fix for https://jira.nuxeo.com/browse/NXP-11348

This time, getPathFragments() looks for a Domain or a subtype of Domain. I left a test for the root path to avoid infinite loops in all situations (e.g. a publication tree not based on a domain).

### CODE REVIEW

**Comment by efge** [comment]
That's better, thanks!
Could you change a few details still:
- add the standard LGPL 2.1 copyright headers (see http://doc.nuxeo.com/display/CORG/Copyright+and+license+headers)
- set the contributor (you) in the copyright header and not as a @author javadoc tag

**Comment by mkalam-alami** [comment]
Ok it's done.

**Comment by mkalam-alami** [comment]
Hi,

Is there still something wrong with this PR?

**Comment by jcarsique** [comment]
Hi,

The JIRA issue was missing an assignee and a fixVersion. Thanks for the revival, we're looking at it now.

**Comment by jcarsique** [comment]
Merged. Can you confirm it's still fine with my changes?

**Pull request closed without merging**
